DROP TABLE UserT IF EXISTS;
DROP TABLE Book IF EXISTS;

CREATE TABLE UserT (
                    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id      LONG,
                    first_name      VARCHAR(30),
                    last_name       VARCHAR(30),
                    age    INTEGER NOT NULL,
                    email    VARCHAR(30)
);
CREATE INDEX User_id_idx ON UserT (user_id);

CREATE TABLE Book (
                     id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title    VARCHAR(100)
);
