DROP TABLE Job_Info IF EXISTS;

CREATE TABLE Job_Info (
                    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id      VARCHAR(32),
                    job_ref      VARCHAR(30),
                    other_ref1    VARCHAR(30),
                    other_ref2    VARCHAR(30),
                    job_external_ref    VARCHAR(30)
);
CREATE INDEX Job_id_idx ON Job_Info (job_id);
